version: '2'
services:
    languageapplication-app:
        image: languageapplication
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://languageapplication-mysql:3306/languageapplication?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    languageapplication-mysql:
        extends:
            file: mysql.yml
            service: languageapplication-mysql
